=head1 NAME 

Form::Data::Processor - yet another form data processor


=head1 DESCRIPTION

Actually it is just another form data validator,  which was inspired by
L<HTML::FormHandler>. It has similar syntax and similar features, except one: it
is B<NOT> a form renderer (but it is written using L<Moose>, so you can extend
it as you wish).


=head1 Form::Data::Processor vs HTML::FormHandler

The main goal was increasing validation speed with saving count of validate
features as possible.

Please look at benchmarks (C<benchmarks> folder in distro).

On my desktop "Intel(R) Core(TM)2 Duo CPU E4600  @ 2.40GHz,4GB, OpenSuSE, Linux 3.11.6-4-pae
(e6d4a27) i686" it looks like:

    $> perl benchmarks/simple.pl
                                  Rate Create HTML::FormHandler Create Form::Data::Processor
    Create HTML::FormHandler     101/s                       --                         -84%
    Create Form::Data::Processor 622/s                     514%                           --
                           Rate Form::Data::Processor     HTML::FormHandler
    Form::Data::Processor 314/s                    --                  -15%
    HTML::FormHandler     369/s                   18%                    --

    ----------------------------------------

    $> perl benchmarks/medium.pl
    1..1
                                   Rate Create HTML::FormHandler Create Form::Data::Processor
    Create HTML::FormHandler     29.4/s                       --                         -39%
    Create Form::Data::Processor 47.9/s                      63%                           --
    ok 1 - Form::Data::Processor "result()" equals to HTML::FormHandler "values()"
                            Rate     HTML::FormHandler Form::Data::Processor
    HTML::FormHandler     49.3/s                    --                  -88%
    Form::Data::Processor  408/s                  728%                    --

    ----------------------------------------

    $> perl benchmarks/complex.pl
    1..2
                                   Rate Create Form::Data::Processor Create HTML::FormHandler
    Create Form::Data::Processor 7.41/s                           --                     -39%
    Create HTML::FormHandler     12.3/s                          65%                       --
    ok 1 - Form::Data::Processor "result()" equals to HTML::FormHandler "values()"
                               Rate    x1 HTML::FormHandler x1 Form::Data::Processor
    x1 HTML::FormHandler     39.5/s                      --                     -85%
    x1 Form::Data::Processor  268/s                    578%                       --
    ok 2 - Form::Data::Processor "result()" equals to HTML::FormHandler "values()"
                                Rate x32 HTML::FormHandler x32 Form::Data::Processor
    x32 HTML::FormHandler     1.47/s                    --                      -95%
    x32 Form::Data::Processor 27.9/s                 1800%                        --



=head1 START HERE

=head2 L<Form::Data::Processor::Form>

=head2 L<Form::Data::Processor::Field>

=head1 SEE ALSO

L<HTML::FormHandler> - form validator and renderer.

=cut
