=head1 NAME 

Form::Data::Processor - yet another form data processor


=head1 DESCRIPTION

Actually it is just another form data validator,  which was inspired by
L<HTML::FormHandler>. It has similar syntax and similar features, except one: it
is B<NOT> a form renderer (but it is written using L<Moose>, so you can extend
it as you wish).


=head1 Form::Data::Processor vs HTML::FormHandler

The main goal was increasing validation speed with saving count of validate
features as possible.

Please look at benchmarks (C<benchmarks> folder in distro).

On my machine "Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz, 8GB, Arch Linux
3.12.5-1-ARCH" it looks like:

    $> perl benchmarks/simple.pl
                                   Rate Create HTML::FormHandler Create Form::Data::Processor
    Create HTML::FormHandler     82.8/s                       --                         -83%
    Create Form::Data::Processor  496/s                     499%                           --

                           Rate Form::Data::Processor     HTML::FormHandler
    Form::Data::Processor 316/s                    --                   -8%
    HTML::FormHandler     345/s                    9%                    --

    ----------------------------------------

    $> perl benchmarks/medium.pl
    1..1
                                   Rate Create HTML::FormHandler Create Form::Data::Processor
    Create HTML::FormHandler     23.2/s                       --                         -43%
    Create Form::Data::Processor 40.6/s                      75%                           --

    ok 1 - Form::Data::Processor "result()" equals to HTML::FormHandler "values()"

                            Rate     HTML::FormHandler Form::Data::Processor
    HTML::FormHandler     37.4/s                    --                  -90%
    Form::Data::Processor  388/s                  937%                    --

    ----------------------------------------

    $> perl benchmarks/complex.pl 
    1..2
                                   Rate Create Form::Data::Processor Create HTML::FormHandler
    Create Form::Data::Processor 5.69/s                           --                     -43%
    Create HTML::FormHandler     10.0/s                          77%                       --

    ok 1 - Form::Data::Processor "result()" equals to HTML::FormHandler "values()"

                               Rate    x1 HTML::FormHandler x1 Form::Data::Processor
    x1 HTML::FormHandler     29.7/s                      --                     -88%
    x1 Form::Data::Processor  242/s                    716%                       --

    ok 2 - Form::Data::Processor "result()" equals to HTML::FormHandler "values()"

                                Rate x32 HTML::FormHandler x32 Form::Data::Processor
    x32 HTML::FormHandler     1.10/s                    --                      -95%
    x32 Form::Data::Processor 23.4/s                 2034%                        --



=head1 START HERE

=head2 L<Form::Data::Processor::Form>

=head2 L<Form::Data::Processor::Field>

=head1 SEE ALSO

L<HTML::FormHandler> - form validator and renderer.

=cut
